apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
      tolerations:
        - key: "k8s-pods-simulator.io/provider"
          operator: "Equal"
          value: "mock"
          effect: "NoSchedule"
      nodeSelector:
        type: k8s-pods-simulator