apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
  tolerations:
    - key: "k8s-pods-simulator.io/provider"
      operator: "Equal"
      value: "mock"
      effect: "NoSchedule"
  nodeSelector:
    type: k8s-pods-simulator